import T from '../theme/tokens.js';

export const PROJECT_STAGES = ["pitching", "current", "archived"];
export const STAGE_LABELS = { pitching: "Pitching", current: "Current", archived: "Archived" };
export const STAGE_COLORS = { pitching: T.gold, current: T.pos, archived: T.dim };
export const STATUS_COLORS = { todo: "rgba(250,250,249,.4)", progress: "#22D3EE", roadblocked: "#F87171", done: "#34D399" };
export const STATUS_LABELS = { todo: "To Do", progress: "In Progress", roadblocked: "Roadblocked", done: "Done" };
export const DOC_TYPES = ["invoice", "w9", "w2", "contract"];
export const DOC_TYPE_COLORS = { invoice: "#FFEA97", w9: "#22D3EE", w2: "#E879F9", contract: "#60A5FA" };
export const PAYMENT_COLORS = { none: "rgba(250,250,249,.4)", invoiced: "#FBBF24", partial: "#FB923C", paid: "#34D399" };
export const PAYMENT_LABELS = { none: "No Invoice", invoiced: "Invoiced", partial: "Partial", paid: "Paid" };
export const W9_COLORS = { pending: "rgba(250,250,249,.4)", received: "#FBBF24", approved: "#34D399" };
export const VENDOR_TYPES = ["venue", "catering", "av", "fabrication", "staffing", "print", "photo_video", "floral", "talent", "freight", "rental", "freelance", "other"];
export const VENDOR_TYPE_LABELS = { venue: "Venue", catering: "Catering & Bev", av: "AV / Sound", fabrication: "Fabrication", staffing: "Staffing", print: "Print", photo_video: "Photo / Video", floral: "Floral", talent: "Talent", freight: "Freight / Logistics", rental: "Rental", freelance: "Freelance", other: "Other" };
export const VENDOR_TYPE_COLORS = { venue: "#FFEA97", catering: "#34D399", av: "#22D3EE", fabrication: "#E879F9", staffing: "#60A5FA", print: "#FB923C", photo_video: "#F87171", floral: "#A3E635", talent: "#FBBF24", freight: "#C084FC", rental: "#22D3EE", freelance: "#F472B6", other: "rgba(250,250,249,.5)" };
export const INVOICE_KINDS = ["deposit", "final", "addendum"];
export const INVOICE_KIND_LABELS = { deposit: "Deposit", final: "Final", addendum: "Addendum" };
export const INVOICE_KIND_COLORS = { deposit: "#22D3EE", final: "#FFEA97", addendum: "#E879F9" };
export const CLIENT_FILE_CATS = ["rfp", "brief", "design", "contract", "deck", "reference", "other"];
export const CLIENT_FILE_LABELS = { rfp: "RFP", brief: "Brief", design: "Design Files", contract: "Contract", deck: "Deck / Presentation", reference: "Reference", other: "Other" };
export const CLIENT_FILE_COLORS = { rfp: "#FFEA97", brief: "#22D3EE", design: "#E879F9", contract: "#60A5FA", deck: "#FB923C", reference: "#A3E635", other: "rgba(250,250,249,.5)" };
export const ROLES = ["admin", "producer", "viewer"];
export const ROLE_LABELS = { admin: "Admin", producer: "Producer", viewer: "Viewer" };
export const ROLE_COLORS = { admin: T.gold, producer: T.cyan, viewer: T.dim };
export const PERMISSION_LABELS = { budget: "Budget", timeline: "Timeline", vendors: "Vendors", pnl: "P&L", docs: "Documents", ros: "Run of Show", client: "Client View", ai: "AI Assistant", settings: "Settings" };
export const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID || "";
